### ISSUE TITLE
Animal Sounds WAY to loud. FIX IT PLEASE.

### ISSUE THREAD

**Issue by neoshifter39** [daipenger/Sound-Physics#17]
I am going INSANE because animals sounds are WAY over amplified and the distance you hear them at is over amplified . You need to WAY soften the animal sounds over distances and make them quieter. This NEEDS to be FIXED.
It just sounds like there is 100 animals right at my ear every where i go.
 DO NOT MAKE THIS CLOSED BECAUSE YOU DON'T THINK ITS AN ISSUE.

**Comment by daipenger** [comment]
Turn down globalVolumeMultiplier. And then calm down.

If you want to truly have that issue fixed then fix the attenuation rolloff model in OpenAL. To do quadratic fading by hand I will have to restructure the whole mod and I haven't had the time to do it yet. By being yelled at I also don't want to. GitHub is a place to collaborate and not yell. If you want to have this issue fixed so eagerly do it yourself and make a pull request.

"DO NOT MAKE THIS CLOSED BECAUSE YOU DON'T THINK ITS AN ISSUE." I will not close it because I don't think its an issue. But your attitude annoys me. You have been warned.

**Comment by Lorelando** [comment]
Although this might not concern the technical issue at hand, this concerns once issue with you post, neoshifter39. Github servers as an environment, where people help each other develop something.
However, that help is voluntary. So is the use of the software/mod itself.
In other words, you have no reason to demand a fix, nor do you have any reason to be this rude, let alone yell at someone.
