### ISSUE TITLE
Certain sounds audible from too far away

### ISSUE THREAD

**Issue by nbairen** [daipenger/Sound-Physics#8]
Thanks for putting this update out, but I noticed that a few sounds can be heard at far too high volumes from far to distant. The only sounds that I've seen this occur for are things like droppers, dispensers, doors, etc. Basically, sounds from redstone blocks can be heard from 10+ chunks away as if they were right next to the player.

**Comment by daipenger** [comment]
Yeah, that's correct. The reason is actually documented by SonicEther: All sound files that are not mono are played with full volume and without spatial panning. Most files in the standard ressources are mono, but not all of them. (That's the reason why the SoundFix pack exists, but SonicEther didn't catch all sounds with that) If you use custom sound packs you can only fix it by converting all files by yourself.

Definitely a bug that I will try to find the cause for!

**Comment by daipenger** [comment]
Fixed.

**Comment by nbairen** [comment]
Thank you so much!

**Comment by DarianLStephens** [comment]
I don't know if the fix was worth it. Personally, I don't hear any difference in the volume of sounds anymore, regardless of their distance; I'm either close enough to hear them or I'm not.
Maybe really loud things sound more powerful, but so does everything else. I can no longer tell if something is right next to me or far enough to not worry about.
I've also recorded it, so you can see my example: [https://youtu.be/pF3IJaYl6MA](url)

I recorded two more videos with a more controlled test; a minecart on a loop. I used both versions 1.11.2 and 1.12 for this.
[https://youtu.be/pD6XvFTjbc4](url) 1.11.2
[https://youtu.be/MXuGl4uqPhs](url) 1.12
Sounds can still be heard from farther away, and that's good in all cases. The problem with near sounds being distantially indistinguishable arises mostly in survival mode. 
Mobs don't make sounds beyond a certain distance, and within that distance, there's no noticeable attenuation, which means you can't tell how far mobs are from you. That's a big problem, because you don't know if you should run, fight, or what. This is less of an issue in caves since we have the reverb and closed-area filters, but in open spaces, presumably like the Nether, it's hard.

**Comment by BinToss** [comment]
What if stereo sounds are merged to mono on the fly? Could that be done as a workaround?
